# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

# Charizard Pokemon Theme — Hyprland colors
$activeBorderColor = rgb(cc3300)
$inactiveBorderColor = rgb(008888)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
}
