background            #0f2138
foreground            #fdf4c4

# black
color0  #0f2138
color8  #7893b4

# red
color1  #c56363
color9  #e1a3a3

# green
color2  #76c276
color10 #b1dfb1

# yellow
color3  #cebd7c
color11 #e5dbb2

# blue
color4  #9a98be
color12 #c3c2da

# magenta
color5  #d095d0
color13 #e5bee5

#cyan
color6  #9fd5d5
color14 #c2e7e7

#white
color7  #fdf4c4
color15 #fff7cc


